packageExtensions:
  eslint-plugin-prettier@*:
    peerDependencies:
      eslint-config-prettier: '*'
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      typescript: '*'
  postcss-normalize@*:
    peerDependencies:
      browserslist: '*'
  'react-dev-utils@*':
    peerDependencies:
      typescript: '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      typescript: '*'
      webpack: '*'
  '@storybook/core@*':
    peerDependencies:
      '@storybook/addon-essentials': '*'
      typescript: '*'
      react-is: '*'
  '@storybook/react@*':
    peerDependencies:
      '@storybook/addon-essentials': '*'
      react-is: '*'
      typescript: '*'
      babel-loader: '*'
  '@storybook/addon-essentials@*':
    peerDependencies:
      typescript: '*'
      '@babel/core': '*'
      webpack: '*'
  react-docgen-typescript-loader@*:
    peerDependencies:
      webpack: '*'
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.1.1.cjs
