changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main

packageExtensions:
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': '*'
      typescript: '*'
      webpack: '*'
  '@storybook/addon-essentials@*':
    peerDependencies:
      typescript: '*'
      webpack: '*'
  '@storybook/core@*':
    peerDependencies:
      '@storybook/addon-essentials': '*'
      react-is: '*'
      typescript: '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/mdx1-csf@*':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/react@*':
    peerDependencies:
      '@storybook/addon-essentials': '*'
      babel-loader: '*'
      react-is: '*'
      typescript: '*'
  '@storybook/telemetry@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  eslint-plugin-prettier@*:
    peerDependencies:
      eslint-config-prettier: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
