changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main

packageExtensions:
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': 8
      typescript: '*'
      webpack: '*'
  '@storybook/addon-essentials@*':
    peerDependencies:
      typescript: '*'
      webpack: '*'
  '@storybook/core@*':
    peerDependencies:
      '@storybook/addon-essentials': '*'
      react-is: '*'
      typescript: '*'
  '@storybook/react@*':
    peerDependencies:
      '@storybook/addon-essentials': '*'
      babel-loader: '*'
      react-is: '*'
      typescript: '*'
  eslint-plugin-prettier@*:
    peerDependencies:
      eslint-config-prettier: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
